name: Deploy to Nginx

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Install Nginx (if not installed)
    #   run: |
    #     if ! command -v nginx > /dev/null; then
    #       sudo apt update
    #       sudo apt install nginx -y
    #     else
    #       echo "Nginx is already installed."
    #     fi

    - name: Clean old Nginx HTML files
      run: |
        sudo rm -rf /var/www/html/*
    
    - name: Copy site to Nginx web root
      run: |
        sudo cp -r ./* /var/www/html/
        sudo chown -R www-data:www-data /var/www/html

    - name: Reload Nginx
      run: |
        sudo systemctl reload nginx
