name: Deploy Website to Nginx Server

on:
  push:
    branches: [ main ]  # Trigger deployment when code is pushed to the main branch
  pull_request:
    branches: [ main ]  # Optionally run on pull requests to test deployment
  workflow_dispatch:    # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to Nginx
      run: |
        # Create a backup of the current deployment
        sudo mkdir -p /var/backups/website
        sudo cp -r ${{ vars.NGINX_ROOT_DIR }}/* /var/backups/website/ || true
        
        # Deploy the files to Nginx web root
        sudo mkdir -p ${{ vars.NGINX_ROOT_DIR }}
        sudo cp -r ./* ${{ vars.NGINX_ROOT_DIR }}/
        
        # Set proper ownership and permissions
        sudo chown -R www-data:www-data ${{ vars.NGINX_ROOT_DIR }}/
        sudo chmod -R 755 ${{ vars.NGINX_ROOT_DIR }}/
        
        # Reload Nginx to apply any configuration changes
        sudo systemctl reload nginx
      
    - name: Verify deployment
      run: |
        echo "Deployment completed! Verifying website is accessible..."
        curl -sSf http://localhost > /dev/null || (echo "Website verification failed" && exit 1)
        echo "Website successfully deployed and verified!
        
        # Log the deployment
        echo "Website deployed at $(date)" >> /var/log/website-deployments.log